[tasks.build]
command = "cargo"
args = ["build"]

[tasks.btest]
dependencies = ["build"]
command = "bash"
args = ["test.sh"]

[tasks.drun]
script = """
#!/bin/bash
cargo run --bin compile -- ${@} > tmp.s
cc -o tmp tmp.s
echo "--- compilier results ---"
./tmp
echo $?
echo "--- fin ---"
"""

[tasks.dot]
script = """
#!/bin/bash
cargo run --bin dot -- ${@} > tmp.dot
"""

[tasks.ast]
dependencies = ["dot"]
script = """
#!/bin/bash
dot -Tpng tmp.dot -o tmp.png
"""

[tasks.push]
script = """
#!/bin/bash

set -eu
cargo readme > README.md
git add README.md
git commit -m "update README by cargo-readme"
git push origin main
"""